services:
  app:
    image: compiler
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - code_volume:/app/code       # Use the named volume 'code_volume' mounted to /code
      - /var/run/docker.sock:/var/run/docker.sock # Mount Docker socket
    env_file:
      - .env
    command: npm run start

volumes:
  code_volume:  
    name: code_volume
